name: Docker Image CI

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --platform=linux/arm64/v8 --tag my-image-name:$(date +%s)
